"""
generate_reports.py
---------------------
Produces the required deliverable reports:
- Dataset Summary
- Model Performance Report
- Energy Consumption Report
- Monthly Usage Forecast (sample households)
- Recommendation Summary
Exports as CSV and a combined Excel workbook.
"""

import pandas as pd
import numpy as np
import joblib
import os
import sys
sys.path.append("/home/claude/energy_project/src")
from recommendations import estimate_bill, efficiency_score, peak_usage_hours, generate_recommendations

DATA_PATH = "/home/claude/energy_project/data/energy_dataset_cleaned.csv"
MODEL_READY_PATH = "/home/claude/energy_project/data/energy_dataset_model_ready.csv"
MODEL_DIR = "/home/claude/energy_project/models"
REPORT_DIR = "/home/claude/energy_project/reports"
TARGET = "Daily_Electricity_Consumption_kWh"

df = pd.read_csv(DATA_PATH)
df_model = pd.read_csv(MODEL_READY_PATH)
model = joblib.load(os.path.join(MODEL_DIR, "best_model.pkl"))
with open(os.path.join(MODEL_DIR, "best_model_name.txt")) as f:
    best_model_name = f.read().strip()

# 1. Dataset Summary
dataset_summary = pd.DataFrame({
    "Metric": ["Total Records", "Total Features", "Missing Values (post-cleaning)",
               "Duplicate Rows (post-cleaning)", "Target Variable", "Avg Daily Consumption (kWh)",
               "Min Daily Consumption (kWh)", "Max Daily Consumption (kWh)"],
    "Value": [len(df), df.shape[1] - 1, df.isna().sum().sum(), df.duplicated().sum(),
              TARGET, round(df[TARGET].mean(), 2), round(df[TARGET].min(), 2), round(df[TARGET].max(), 2)]
})
dataset_summary.to_csv(os.path.join(REPORT_DIR, "1_dataset_summary.csv"), index=False)

# 2. Model Performance Report (already generated by train_models.py, re-load & re-save under standard name)
model_perf = pd.read_csv(os.path.join(REPORT_DIR, "model_performance.csv"))
model_perf.to_csv(os.path.join(REPORT_DIR, "2_model_performance_report.csv"), index=False)

# 3. Energy Consumption Report — aggregated insights
consumption_report = df.groupby(["Season", "House_Type"])[TARGET].agg(
    ["mean", "min", "max", "count"]).reset_index()
consumption_report.columns = ["Season", "House_Type", "Avg_kWh", "Min_kWh", "Max_kWh", "Sample_Count"]
consumption_report.to_csv(os.path.join(REPORT_DIR, "3_energy_consumption_report.csv"), index=False)

# 4. Monthly Usage Forecast — for 10 representative sample households
sample_rows = df_model.drop(columns=[TARGET]).sample(10, random_state=1)
preds = model.predict(sample_rows)
forecast_rows = []
for i, (idx, row) in enumerate(sample_rows.iterrows()):
    daily = max(preds[i], 0.5)
    monthly_kwh, bill = estimate_bill(daily)
    forecast_rows.append({
        "Household_Sample_ID": idx,
        "Predicted_Daily_kWh": round(daily, 2),
        "Predicted_Monthly_kWh": round(monthly_kwh, 2),
        "Estimated_Monthly_Bill_PKR": round(bill, 2),
        "Efficiency_Score": efficiency_score(daily),
    })
monthly_forecast = pd.DataFrame(forecast_rows)
monthly_forecast.to_csv(os.path.join(REPORT_DIR, "4_monthly_usage_forecast.csv"), index=False)

# 5. Recommendation Summary — for the same 10 sample households
rec_rows = []
for i, (idx, row) in enumerate(sample_rows.iterrows()):
    daily = max(preds[i], 0.5)
    monthly_kwh, bill = estimate_bill(daily)
    eff = efficiency_score(daily)
    inputs = {
        "ac_hours": row.get("AC_Usage_Hours", 0),
        "fan_hours": row.get("Fan_Usage_Hours", 0),
        "season": "Summer",  # placeholder context for text generation
        "washing_hours": row.get("Washing_Machine_Usage_Hours", 0),
        "lighting_hours": row.get("Lighting_Hours", 0),
    }
    recs = generate_recommendations(inputs, daily, monthly_kwh, bill, eff)
    rec_rows.append({
        "Household_Sample_ID": idx,
        "Recommendations": " | ".join(recs)
    })
rec_summary = pd.DataFrame(rec_rows)
rec_summary.to_csv(os.path.join(REPORT_DIR, "5_recommendation_summary.csv"), index=False)

# Combined Excel workbook
excel_path = os.path.join(REPORT_DIR, "Energy_Project_Reports.xlsx")
with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:
    dataset_summary.to_excel(writer, sheet_name="Dataset Summary", index=False)
    model_perf.to_excel(writer, sheet_name="Model Performance", index=False)
    consumption_report.to_excel(writer, sheet_name="Consumption Report", index=False)
    monthly_forecast.to_excel(writer, sheet_name="Monthly Forecast", index=False)
    rec_summary.to_excel(writer, sheet_name="Recommendations", index=False)

print("All reports generated in:", REPORT_DIR)
print("Combined Excel workbook:", excel_path)
